### ISSUE TITLE
在服务器中输入readme文档中指令出现下面问题   我想在sver00服务器上面搭建rustdesk服务  请大佬指导   thanks

### ISSUE THREAD

**Issue by acnihao** [n-connect/rustd-hbbx#1]
[acnihao@s8]:<~>$ -pw adduser rustdesk -d /nonexistent -s /usr/sbin/nologin -c "Rustdesk Server user"
-bash: -pw: command not found

**Comment by n-connect** [comment]
Copy paste only the actual command from the README.md, you can see them having `different background`, than the others.

Samples around the `pw` command:

```
[root@srv ~]# pw --help
usage:
  pw [user|group|lock|unlock] [add|del|mod|show|next] [help|switches/values]
[root@srv ~]# which pw
/usr/sbin/pw
[root@srv ~]#
```

**Comment by n-connect** [comment]
For your information the rustdesk-server for FreeBSD package here is outdated, since my and others' [PRs at the original Github code](https://github.com/rustdesk/rustdesk-server/pulls?q=is%3Apr+is%3Aclosed+freebsd) for FreeBSD direct releases was merged.

However the commands are good though. 

You better off using/installing rustdesk-server in this order:
- 1. If you need alwas the fresh newest you can download it from the original GitHub repo, the link/version today is v1.1.11-1 [rustdesk-server-linux-amd64fb.zip](https://github.com/rustdesk/rustdesk-server/releases/download/1.1.11-1/rustdesk-server-linux-amd64fb.zip)
- 2. use FreeBSD-s binary package management to install rustdesk-server. Sometimes they are a bit older than the Github release `pkg install rustdesk-server`, but you can switch to the [latest version](https://docs.freebsd.org/en/books/handbook/ports/#quarterly-latest-branch) of ports collection instead of the Quarterly one
- 3. Do compile it within FreeBSD, via [ports](https://docs.freebsd.org/en/books/handbook/ports/#ports-poudriere)
